config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'subreddits#index'

  get 'subreddits/new'
  get 'subreddits' => 'subreddits#index'
  get 'subreddits/:id' => 'subreddits#show', :as => :subreddit
  get 'comments/new'
  get 'users/new'
  post 'users' => 'users#create'
  put 'users' => 'users#update'
  delete 'users' => 'users#destroy'

  post 'posts' => 'posts#create'
  put 'posts' => 'posts#update'
  delete 'posts' => 'posts#destroy'

  put 'comments' => 'comments#update'
  delete 'comments' => 'comments#destroy'
  post 'comments' => 'comments#create'

  post 'subreddits' => 'subreddits#create'
  post 'subreddits' => 'subreddits#update'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :post
    validates :content, presence: true
    has_many :votes, as: :votable
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
    has_many :comments
    belongs_to :subreddit
    validates :title, presence: true
    validates :content, presence: true
    has_many :votes, as: :votable
end

app/models/subreddit.rb
class Subreddit < ActiveRecord::Base
    has_many :posts
    validates :title, presence: true, length: { maximum: 300 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :votes
  validates :email, presence: true, length: { maximum: 255 }
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :votable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end

  def update
      comment = Comment.find(params[:id])
      comment.content = comment_params["content"]
      comment.save
  end

  def destroy
      Comment.find(params[:id]).destroy
      flash[:success] = "Comment deleted"
  end

  def create
      comment = Comment.new(comment_params)
      comment.save
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create

    # logic goes here
    # ACTUALLY CREATE THE POST HERE

    post = Post.new(post_params)
    post.save

    # redirect, send http response code, or render a template
    # The default action: render "posts/create"
    # The default runs only if there is no redirect, other render action, or
    # head call.
  end

  def update
    post = Post.find(params[:id])
    post.title = post_params["title"]
    post.content = post_params["content"]
    post.save
  end

  def destroy
    Post.find(params[:id]).destroy
    flash[:success] = "Post deleted"

  end

private
  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/subreddits_controller.rb
class SubredditsController < ApplicationController
  def new
  end

  def create
    subreddit = Subreddit.new(subreddit_params)
    subreddit.save
  end

  def update
      subreddit = Subreddit.find(params[:id])
      subreddit.title = subreddit_params["title"]
      subreddit.save
  end

  def index
    @subreddits = Subreddit.all
    # render "subreddits/index" (implied)
  end

  def show
    @subreddit = Subreddit.find(params[:id])
  end

  private
  def subreddit_params
      params.require(:subreddit).permit(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    user = User.new(user_params)
    user.save
  end

  def update
    user = User.find(params[:id])
    user.email = user_params[:email]
    # user.email = user_params["email"]
    user.save
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"

  end

private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/subreddits_helper.rb
module SubredditsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WillDelete</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
<%= button_to "log out", destroy_user_session_path, method: :delete %>
<% else %>
<%= button_to "log in", new_user_session_path %>
<% end %>
<br>
<%= yield %>

</body>
</html>

app/views/posts/create.html.erb
Post was created

app/views/posts/destroy.html.erb
Destroy was created

app/views/posts/update.html.erb
Update was created

app/views/subreddits/index.html.erb
index was created
<ul>
  <% @subreddits.each do |subr| %>
  <li>
    <!-- <%= link_to subr.title, "subreddits/#{subr.id}" %> -->
    <%= link_to subr.title, subreddit_path(subr.id) %>
  </li>
  <% end %>
</ul>

app/views/subreddits/new.html.erb
<h1>Subreddits#new</h1>
<p>Find me in app/views/subreddits/new.html.erb</p>

app/views/subreddits/show.html.erb
<%= @subreddit.title %>

app/views/users/create.html.erb
User was created

app/views/users/destroy.html.erb
User was destroyed

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/update.html.erb
User was updated